name: CI/CD Pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, develop ]

jobs:
  greeting:
    name: Print greeting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Hello CI/CD
        run: echo "Hello CI/CD!"

  python-lint:
    name: Lint Python code
    runs-on: ubuntu-latest
    needs: greeting
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install pylint
        run: pip install pylint
      
      - name: Run pylint
        run: pylint --recursive=y . || echo "Pylint found issues"

  js-lint:
    name: Lint JavaScript
    runs-on: ubuntu-latest
    needs: greeting
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install ESLint
        run: npm install -g eslint
      
      - name: Run ESLint
        run: eslint . || echo "ESLint found issues"
